# Generated by Django 6.0.5 on 2026-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='routing_fue_lat_5fdb4a_idx'), models.Index(fields=['state', 'city'], name='routing_fue_state_217c0f_idx')],
            },
        ),
    ]
